// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_FCflT__KpCumrLOLA2ZwNjuwqSl9kQ',
    appId: '1:855262203450:web:97a75b998a80107ef52f03',
    messagingSenderId: '855262203450',
    projectId: 'terralink-e3415',
    authDomain: 'terralink-e3415.firebaseapp.com',
    storageBucket: 'terralink-e3415.firebasestorage.app',
    measurementId: 'G-ZDEZL4QY3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnXNS6xweKPpqy_rvK-JT_yXKhIo1WXI',
    appId: '1:855262203450:android:222777d6a9432d5df52f03',
    messagingSenderId: '855262203450',
    projectId: 'terralink-e3415',
    storageBucket: 'terralink-e3415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7KTVOITCFlnux5eG_Xvklb1_EVITtKM',
    appId: '1:855262203450:ios:bcbd24a891a073a9f52f03',
    messagingSenderId: '855262203450',
    projectId: 'terralink-e3415',
    storageBucket: 'terralink-e3415.firebasestorage.app',
    iosBundleId: 'com.example.terrariumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP7KTVOITCFlnux5eG_Xvklb1_EVITtKM',
    appId: '1:855262203450:ios:bcbd24a891a073a9f52f03',
    messagingSenderId: '855262203450',
    projectId: 'terralink-e3415',
    storageBucket: 'terralink-e3415.firebasestorage.app',
    iosBundleId: 'com.example.terrariumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_FCflT__KpCumrLOLA2ZwNjuwqSl9kQ',
    appId: '1:855262203450:web:60539fe19eb41325f52f03',
    messagingSenderId: '855262203450',
    projectId: 'terralink-e3415',
    authDomain: 'terralink-e3415.firebaseapp.com',
    storageBucket: 'terralink-e3415.firebasestorage.app',
    measurementId: 'G-5BCMBVHM7G',
  );
}
